[theme]
base = "dark"
primaryColor = "#00A3FF"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0A0A0A"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
fileWatcherType = "auto"

[client]
toolbarMode = "minimal"
